- hosts: all
  gather_facts: yes
  remote_user: ubuntu
  vars:
    base_dir: /home/ubuntu
    playbook_user: ubuntu
    source_path: /home/opc/terraform/privateips/
    destination_path: /home/ubuntu/ansible/ #For Ubuntu 18.04
    contents: "{{ lookup('file', '/home/opc/terraform/ansible/app-servers.conf').splitlines() }}"

  tasks:
    - name: creating base directory
      file:
        path: "{{ base_dir }}/ansible"
        state: directory

    - name: copy ens3 files
      copy:
        remote_src: no
        src: "{{ source_path }}{{ansible_default_ipv4.address}}"
        dest: "{{ destination_path }}"
        mode: u+x
        force: yes

    - name: Write configuration of ens3 to network interfaces
      sudo: yes
      blockinfile:
        path: /etc/network/interfaces
        block: "{{lookup('file', '{{source_path}}{{ansible_default_ipv4.address}}')}}"
        create: no
        state: present

    - name: Install network interface ifupdown
      sudo: yes
      command: apt-get install ifupdown

    - name: Restart network interfaces
      sudo: yes
      command: ifup -a

    - debug:
        msg: "the value of app-servers.conf is {{ item }} {{contents[1]}} {{ansible_all_ipv4_addresses}}"
      with_items: "{{ contents }}"

    - name: get ip
      local_action: shell echo {{ ansible_all_ipv4_addresses }}

    - name: Install apt-get updates
      sudo: yes
      command: apt-get update

    - name: Install haproxy
      sudo: yes
      command: apt-get install -y haproxy

    - name: Templating haproxy config
      sudo: yes
      retries: 3
      delay: 10
      template:
        src: templates/haproxy.cfg.j2
        dest: "{{destination_path}}haproxy.cfg"
        force: yes
      register: result
      until: "'failed' not in result and result.content.find('OK') != -1"

    # - name: Validate haproxy config
    #   command: haproxy -c -f /etc/haproxy/haproxy.cfg

    # - name: Restart haproxy service
    #   sudo: yes
    #   command: service restart haproxy

    # - name: Modify app-server.conf list
    #   delegate_to: 127.0.0.1
    #   replace:
    #     path: /home/opc/terraform/ansible/app-servers.conf
    #     regexp: '\[servers\]\n[^\n]+\n[^\n]+' # Matches [servers] and next two line
    #     replace: "[servers]" # Replace both lines with [servers]

# - hosts: 127.0.0.1
#   connection: local
#   tasks:
# - name: Cleaning local privateips folder
#   shell: rm -rf privateips/*
