- hosts: all
  serial: 1
  gather_facts: yes
  remote_user: ubuntu
  vars:
    base_dir: /home/ubuntu
    playbook_user: ubuntu
    source_path: /home/opc/terraform/privateips/
    app_conf_path: /home/opc/terraform/ansible/
    destination_path: /home/ubuntu/ansible/
    contents: "{{ lookup('file', '/home/opc/terraform/ansible/app-servers.conf').splitlines() }}"

  tasks:
    - name: creating base directory
      file:
        path: "{{ base_dir }}/ansible"
        state: directory

    - name: copy ens3 files
      copy:
        remote_src: no
        src: "{{ source_path }}{{ansible_default_ipv4.address}}"
        dest: "{{ destination_path }}"
        mode: u+x
        force: yes
      run_once: true

    - name: Write configuration of ens3 to network interfaces
      sudo: yes
      blockinfile:
        path: /etc/network/interfaces
        block: "{{lookup('file', '{{source_path}}{{ansible_default_ipv4.address}}')}}"
        create: no
        state: present
      run_once: true

    - name: Install network interface ifupdown
      sudo: yes
      command: apt-get install ifupdown
      run_once: true

    - name: Restart network interfaces
      sudo: yes
      command: ifup -a
      run_once: true
