# redis_playbook.yml
- hosts: 152.67.0.254
  remote_user: opc
  vars:
    base_dir: /home/opc
    replica_count: 1
    playbook_user: opc

  tasks:
  - name: create base directory 
    become: true
    file:
      path: "{{ base_dir }}/ansible"
      state: directory