# redis_playbook.yml
- hosts: "{{variable_host}}" 
  remote_user: opc
  vars:
    base_dir: /home/opc
    replica_count: 1
    playbook_user: opc
    source_path: /home/opc/terraform/privateips/
    destination_path: /etc/sysconfig/network-scripts/

  tasks:
  - name: create base directory 
    become: true
    file:
      path: "{{ base_dir }}/ansible"
      state: directory
  - name: copy ens3 files
    copy:
      remote_src: no
      src: "{{ source_path }}"
      dest: "{{ destination_path }}"
      mode: u+x
      force: yes
    
    