# redis_playbook.yml
- hosts: "{{variable_host}}" 
  remote_user: opc
  vars:
    base_dir: /home/opc
    replica_count: 1
    playbook_user: opc

  tasks:
  - name: create base directory 
    become: true
    file:
      path: "{{ base_dir }}/ansible"
      state: directory
  - name: copy ens3 files
    copy:
      sudo: true
      remote_src: false
      src: "{{ base_dir }}/terraform/privateips/*"
      dest: "/etc/sysconfig/network-scripts/"
      mode: u+x
      force: no
    
    