# redis_playbook.yml
- hosts: "{{variable_host}}" 
  remote_user: ubuntu
  vars:
    base_dir: /home/ubuntu
    playbook_user: ubuntu
    source_path: /home/opc/terraform/privateips/
    destination_path: /home/ubuntu/ansible/ #For Ubuntu 18.04
    contents: "{{ lookup('file', '/home/opc/terraform/ansible/app-servers.conf').splitlines() }}"
  tasks:
  - name: creating base directory 
    become: true
    file:
      path: "{{ base_dir }}/ansible"
      state: directory

  - name: copy ens3 files #Task for Oracle Linux 
    sudo: yes
    copy: 
      remote_src: no
      src: "{{ source_path }}{{variable_host}}"
      dest: "{{ destination_path }}"
      mode: u+x
      force: yes

  - name: Write configuration of ens3 to network interfaces
    sudo: yes
    blockinfile:
      path: /etc/network/interfaces
      block: "{{lookup('file', '{{source_path}}{{variable_host}}')}}"
      create: no
      state: present
  
  - name: Install network interface ifupdown
    sudo: yes
    command: apt-get install ifupdown
  
  - name: Restart network interfaces
    sudo: yes
    command: ifup -a
  
  - name: Template Loop example
    sudo: yes
    template:
        src: templates/privateip.cfg.j2
        dest: "{{destination_path}}haproxy.cfg"
  - debug: 
      msg : "the value of app-servers.conf is {{ item }}"
    with_items: "{{ contents }}"
    
- hosts: 127.0.0.1
  connection: local
  tasks:
  - name: Cleaning local privateips folder
    shell: rm -rf privateips/*
  - name: Delete lines of app-server
    replace:
      path: /home/opc/terraform/ansible/app-servers.conf
      regexp: '\[servers\]\n[^\n]+\n[^\n]+' # Matches [servers] and next two line
      replace: '[servers]'          # Replace both lines with [servers]