# redis_playbook.yml
- hosts: "{{variable_host}}" 
  remote_user: ubuntu
  vars:
    base_dir: /home/ubuntu
    playbook_user: ubuntu
    source_path: /home/opc/terraform/privateips/
    destination_path: /home/ubuntu/ansible/ #For Ubuntu 18.04
    # contents: "{{ lookup('file', '/home/opc/terraform/ansible/app-servers.conf').splitlines() }}"
  tasks:
  - name: creating base directory 
    become: true
    file:
      path: "{{ base_dir }}/ansible"
      state: directory

  - name: copy ens3 files #Task for Oracle Linux 
    sudo: yes
    copy: 
      remote_src: no
      src: "{{ source_path }}{{variable_host}}"
      dest: "{{ destination_path }}"
      mode: u+x
      force: yes

  - name: Write configuration of ens3 to network interfaces
    blockinfile:
      path: /etc/network/interfaces
      block: "{{lookup('file', '/home/ubuntu/ansible/{{variable_host}}')}}"
      create: no
      state: present

  # - name: Recursively find files #Task for Oracle Linux
  #   shell: "ip a | grep ens3: | sed \"1 d\""
  #   register: files

  # - name: Display all variables/facts known for a host #Task for Oracle Linux
  #   debug:
  #     var: files
  # - set_fact:
  #     stdout_lines: "{{ files.stdout_lines }}"
  #   with_items: "{{ files.stdout_lines }}"
  # - debug:
  #     msg: "This is a stdout line: {{ item }}"
  #   with_items: "{{ stdout_lines }}"
  
  # - name : ifup command running  
  #   sudo: true
  #   shell: ifup {{ item }}
  #   with_items: "{{ stdout_lines }}"
  # - debug: var=ansible_all_ipv4_addresses
  # - debug: var=ansible_default_ipv4.address
  
  # - name: Template Loop example
  #   template:
  #       src: templates/privateip.cfg.j2
  #       dest: "/home/opc/haproxy.cfg"
  # - debug: 
  #     msg : "the value of app-servers.conf is {{ item }}"
  #   with_items: "{{ contents }}"