- hosts: all
  serial: 1
  gather_facts: yes
  remote_user: ubuntu
  vars:
    base_dir: /home/ubuntu
    playbook_user: ubuntu
    source_path: /home/ubuntu/
    backup_path: /home/opc/redis-backup/
    redis_rdb_filename: "dump.rdb"
    tenancy_name: 'indiafieldse'

  tasks:
    - name: Copy to host
      delegate_to: 127.0.0.1
      fetch:
        remote_src: yes
        src: "{{ source_path }}{{redis_rdb_filename}}"
        dest: "{{ backup_path }}"


    - name: Renaming rdb from node
      delegate_to: 127.0.0.1
      command: mv {{backup_path}}{{redis_rdb_filename}} {{backup_path}}dump-{{ansible_default_ipv4.address}}.rdb

    - name: Backup sending to Object Storage
      delegate_to: 127.0.0.1
      command: os object put -ns {{tenancy_name}} -bn redis-backup --name {{ backup_path }}dump-{{ansible_default_ipv4.address}}-{{ansible_data_time.iso8601}}.rdb --file dump-{{ansible_default_ipv4.address}}.rdb