# redis_playbook.yml
- hosts: "{{variable_host}}" 
  remote_user: opc
  vars:
    base_dir: /home/opc
    replica_count: 1
    playbook_user: opc

  tasks:
  - name: create base directory 
    become: true
    file:
      path: "{{ base_dir }}/ansible"
      state: directory
  - name: copying all ens3 files
    become: true
    sudo: yes
    copy:
      src: /privateips/*
      dest: /etc/sysconfig/network-scripts/
    
    