# redis_playbook.yml
- hosts: 152.67.0.254
  remote_user: opc
  vars:
    base_dir: /home/opc
    replica_count: 1
    playbook_user: opc

  tasks:
  - name: copy files to server
    copy:
      remote_src: true
      src: /home/opc/ansible/extra-ips.sh
      dest: /home/opc
      mode: u+x
      force: no