# redis_playbook.yml
- hosts: "{{variable_host}}" 
  remote_user: opc
  vars:
    base_dir: /home/opc
    playbook_user: opc
    source_path: /home/opc/terraform/privateips/
    destination_path: /etc/sysconfig/network-scripts/

  tasks:
  - name: create base directory 
    become: true
    file:
      path: "{{ base_dir }}/ansible"
      state: directory

  - name: copy ens3 files
    sudo: true
    copy: 
      remote_src: no
      src: "{{ source_path }}"
      dest: "{{ destination_path }}"
      mode: u+x
      force: yes
    
  # - name: Initialize added Private IPs
  #   sudo: true
  #   command: reboot 
  #   run_once: true
- hosts: 127.0.0.1
  connection: local
  tasks:
  - name: Recursively find files
    find:
      paths: "{{source_path}}"
      recurse: yes
    register: dir_files
  - name: Display all variables/facts known for a host
    debug:
      var: dir_files