# redis_playbook.yml
- hosts: "{{variable_host}}" 
  remote_user: opc
  vars:
    base_dir: /home/opc
    playbook_user: opc
    source_path: /home/opc/terraform/privateips/
    destination_path: /etc/sysconfig/network-scripts/

  tasks:
  - name: create base directory 
    become: true
    file:
      path: "{{ base_dir }}/ansible"
      state: directory

  - name: copy ens3 files
    sudo: true
    copy: 
      remote_src: no
      src: "{{ source_path }}"
      dest: "{{ destination_path }}"
      mode: u+x
      force: yes
    
  # - name: Initialize added Private IPs
  #   sudo: true
  #   command: reboot 
  #   run_once: true
  - name: Recursively find files
    shell: "ls {{ destination_path }} | grep ens3:"
    register: files
    # find:
    #   paths: "{{ destination_path }}"
    #   recurse: yes
    #   use_regex: true
    #   pattern: ['.ens3:']
    # register: dir_files
  - name: Display all variables/facts known for a host
    debug:
      var: files.stdout_lines
  - set_fact:
      stdout_lines: "{{ files.stdout_lines }}"
    with_items: "{{ files.stdout_lines.results }}"
  - debug:
      msg: "This is a stdout line: {{ item }}"
    with_items: "{{ stdout_lines }}"
  # - name: Start all ifup using the above matched configs
  #   sudo: true
  #   command: ifup dir_files.