# redis_playbook.yml
- hosts: 152.67.0.254
  remote_user: opc
  vars:
    base_dir: /home/opc
    replica_count: 1
    playbook_user: opc

  tasks:
  - name: Update repos
    shell: sudo yum update -y
    run_once: true