- hosts: all
  serial: 1
  gather_facts: true
  remote_user: ubuntu
  vars:
    base_dir: /home/ubuntu
    playbook_user: ubuntu
    source_path: /home/ubuntu/ #Remote redis machine source path
    backup_path: /home/opc/redis-backup/ #Localhost backup path
    redis_rdb_filename: "dump.rdb"
    dump_name: "dump-{{ ansible_default_ipv4.address }}.rdb"
    backup_file_name: "redis-backup-{{ansible_default_ipv4.address}}-{{ lookup('pipe','date +%Y-%m-%d-%H:%M:%S') }}.rdb"

  tasks:
    - name: Create redis-backup if it doesn't exist
      delegate_to: 127.0.0.1
      file:
        path: "{{ backup_path }}"
        state: directory

    - name: Copy to host
      fetch:
        src: "{{redis_rdb_filename}}"
        dest: "{{ backup_path }}"

    - name: Renaming rdb from node
      delegate_to: 127.0.0.1
      command: mv {{backup_path}}{{ansible_default_ipv4.address}}/{{redis_rdb_filename}} {{backup_path}}{{dump_name}}

    - name: Backup sending to Object Storage
      delegate_to: 127.0.0.1
      delegate_facts: true
      shell: oci os object put -bn redis-backup --name {{backup_file_name}} --file {{backup_path}}{{dump_name}}
