- hosts: all
  serial: 1
  gather_facts: true
  remote_user: ubuntu
  vars:
    base_dir: /home/ubuntu
    playbook_user: ubuntu
    restore_path: /home/ubuntu/ #Remote redis machine source path
    source_path: /home/opc/terraform/redis-backup/redis-restore-data/ #Localhost backup path
    redis_rdb_filename: "dump.rdb"
    dump_name: "dump.rdb"
    backup_redis_filename: "redis-backup-10.0.1.172-2019-11-10-18:10:12.rdb" #Name as per RDB backup in object storage

  tasks:
    - name: Create redis-backup if it doesn't exist
      delegate_to: 127.0.0.1
      file:
        path: "{{ source_path }}"
        state: directory

    - name: Download backup from object storage
      delegate_to: 127.0.0.1
      shell: oci os object get -bn redis-backup --name {{backup_redis_filename}} --file {{backup_redis_filename}}

    - name: Copying rdb to redis node
      copy:
        remote_src: false
        src: "{{ source_path }}{{backup_redis_filename}}"
        dest: "{{ restore_path }}"

    - name: Rename rdb
      command: mv {{ restore_path }}{{ backup_redis_filename }} {{dump_name}}
